python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1004 --data-probs 0 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1005 --data-probs 0 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1006 --data-probs 0 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1007 --data-probs 0 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1008 --data-probs 0 --save-result True --descript "wav phrase resnet18 speaker independent"

python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1004 --data-probs 1 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1005 --data-probs 1 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1006 --data-probs 1 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1007 --data-probs 1 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1008 --data-probs 1 --save-result True --descript "wav phrase resnet18 speaker independent"

python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1004 --data-probs 2 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1005 --data-probs 2 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1006 --data-probs 2 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1007 --data-probs 2 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1008 --data-probs 2 --save-result True --descript "wav phrase resnet18 speaker independent"


python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1004 --data-probs 3 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1005 --data-probs 3 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1006 --data-probs 3 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1007 --data-probs 3 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1008 --data-probs 3 --save-result True --descript "wav phrase resnet18 speaker independent"

python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1004 --data-probs 4 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1005 --data-probs 4 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1006 --data-probs 4 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1007 --data-probs 4 --save-result True --descript "wav phrase resnet18 speaker independent"
python train.py --wandb True --batch-size 16 --model efficient_b0 --dataset phrase --tag efficient_b0 wav phrase set100 --seed 1008 --data-probs 4 --save-result True --descript "wav phrase resnet18 speaker independent"
