python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set100 --seed 1004 --data-probs 0 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set100 --seed 1005 --data-probs 0 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set100 --seed 1006 --data-probs 0 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set100 --seed 1007 --data-probs 0 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set100 --seed 1008 --data-probs 0 --save-result True --descript "wav phrase se_resnet101 speaker independent"

python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set20 --seed 1004 --data-probs 1 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set20 --seed 1005 --data-probs 1 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set20 --seed 1006 --data-probs 1 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set20 --seed 1007 --data-probs 1 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set20 --seed 1008 --data-probs 1 --save-result True --descript "wav phrase se_resnet101 speaker independent"

python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set40 --seed 1004 --data-probs 2 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set40 --seed 1005 --data-probs 2 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set40 --seed 1006 --data-probs 2 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set40 --seed 1007 --data-probs 2 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set40 --seed 1008 --data-probs 2 --save-result True --descript "wav phrase se_resnet101 speaker independent"


python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set60 --seed 1004 --data-probs 3 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set60 --seed 1005 --data-probs 3 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set60 --seed 1006 --data-probs 3 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set60 --seed 1007 --data-probs 3 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set60 --seed 1008 --data-probs 3 --save-result True --descript "wav phrase se_resnet101 speaker independent"

python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set80 --seed 1004 --data-probs 4 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set80 --seed 1005 --data-probs 4 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set80 --seed 1006 --data-probs 4 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set80 --seed 1007 --data-probs 4 --save-result True --descript "wav phrase se_resnet101 speaker independent"
python train.py --wandb True --batch-size 16 --model se_resnet101 --dataset phrase --tag se_resnet101 wav phrase set80 --seed 1008 --data-probs 4 --save-result True --descript "wav phrase se_resnet101 speaker independent"
