python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set100 --seed 1004 --data-probs 0 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set100 --seed 1005 --data-probs 0 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set100 --seed 1006 --data-probs 0 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set100 --seed 1007 --data-probs 0 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set100 --seed 1008 --data-probs 0 --save-result True --descript "wav phrase alexnet speaker independent"

python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set20 --seed 1004 --data-probs 1 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set20 --seed 1005 --data-probs 1 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set20 --seed 1006 --data-probs 1 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set20 --seed 1007 --data-probs 1 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set20 --seed 1008 --data-probs 1 --save-result True --descript "wav phrase alexnet speaker independent"

python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set40 --seed 1004 --data-probs 2 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set40 --seed 1005 --data-probs 2 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set40 --seed 1006 --data-probs 2 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set40 --seed 1007 --data-probs 2 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set40 --seed 1008 --data-probs 2 --save-result True --descript "wav phrase alexnet speaker independent"


python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set60 --seed 1004 --data-probs 3 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set60 --seed 1005 --data-probs 3 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set60 --seed 1006 --data-probs 3 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set60 --seed 1007 --data-probs 3 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set60 --seed 1008 --data-probs 3 --save-result True --descript "wav phrase alexnet speaker independent"

python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set80 --seed 1004 --data-probs 4 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set80 --seed 1005 --data-probs 4 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set80 --seed 1006 --data-probs 4 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set80 --seed 1007 --data-probs 4 --save-result True --descript "wav phrase alexnet speaker independent"
python train.py --wandb True --batch-size 16 --model alexnet --dataset phrase --tag alexnet wav phrase set80 --seed 1008 --data-probs 4 --save-result True --descript "wav phrase alexnet speaker independent"
